### ISSUE TITLE
Firebase keys

### ISSUE THREAD

**Issue by LittleFrosty** [ViktorAtanasof/bulmarks#1]
Not sure if it's intentional but your firebase keys are public

**Comment by ViktorAtanasof** [comment]
Hi, LittleFrosty!

Thank you for bringing this to my attention. I appreciate your concern. However, I want to clarify that the Firebase keys are intentionally public as they are needed for the project to function properly. I have created necessary Firebase security rules to ensure the safety and integrity of the data. If you have any further questions or concerns, please don't hesitate to reach out.
